apiVersion: v1
kind: Service
metadata:
  name: mistral-ai-instruct-service
spec:
  selector:
    app: mistral-ai-instruct-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
