site_name: Intellithing - Mistral AI Instruction model
site_author: Srushanth Baride
nav:
  - Home: "index.md"
  - Project Setup: "Project-Setup.md"
  - Deployment: "Deployment.md"
  - Code: "Code.md"

site_description: >-
  This is my site description.

# Configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en

# Repository
repo_name: Srushanth/Intellithing-Mistral-AI
repo_url: https://github.com/Srushanth/Intellithing-Mistral-AI

# Connect with me.
extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/Srushanth/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/srushanth-baride/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/srushanthbaride2010
    - icon: fontawesome/brands/google
      link: https://g.dev/SrushanthBaride

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings
  - macros

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

copyright: |
  &copy; 2024 <a href="https://github.com/Srushanth/"  target="_blank" rel="noopener">Srushanth Baride</a>
