apiVersion: v1
kind: Pod
metadata:
  name: 2048-pod
  labels:
    name: 2048-ws
spec:
  containers:
  - name: 2048-container
    image: 926015110176.dkr.ecr.eu-north-1.amazonaws.com/intellithing:prod
    ports:
      - containerPort: 8080
