---
apiVersion: v1
kind: Namespace
metadata:
  name: mistral-ai
---
apiVersion: v1
kind: Service
metadata:
  namespace: mistral-ai
  name: service-mistral-ai
spec:
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-mistral-ai
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: mistral-ai
  name: ingress-mistral-ai
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-mistral-ai
              port:
                number: 7860
