apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 926015110176.dkr.ecr.eu-north-1.amazonaws.com/intellithing@sha256:041d62ead7f456ae57293b8a1ef8024ea59ca8b6e83c3f656430ffb173cbfb6b
          ports:
            - containerPort: 8080
          args:
          - "nvidia-smi"
          resources:
            limits:
              nvidia.com/gpu: 1
    